### PR TITLE
Issue 45

### PR DESCRIPTION
**Pull request by jnstahl**
add missing NEARBY_DEVICES permission to android manifest

### CODE REVIEW

**Comment by jnstahl** [comment]
windows build failure should be fixed by pull request #50

**Review by Nimrodda — APPROVED** [review]
Thanks for the fix. I commented on your other PR though so can't merge.

**Comment by jnstahl** [comment]
dont forget to merge this one

**Comment by Nimrodda** [comment]
> dont forget to merge this one

I would like to merge it but the windows build is still failing unfortunately...
but it's not related to your PR of course
it would be great if you can have a look 🙏

**Comment by jnstahl** [comment]
the windows build was failing before - it is fixed with the other PR

**Comment by Nimrodda** [comment]
yes, sorry. I forgot that this branch was not rebased with master branch that had the fix. All good. Thanks! :)

**Pull request merged**
